version: "3.8"

volumes:
  db-data:

services:
  
  database:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    build:
      context: .
      target: frontend
    command: npm run dev
    volumes:
      - ./frontend:/node/frontend
      - ./public:/node/public
      - /node/frontend/node_modules

  silverstripe:
    image: brettt89/silverstripe-web:7.4-apache
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - database