name: Deploy via SSH

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: "22"
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: "./"
          target: "${{ secrets.REMOTE_DIR }}"
          rm: true

      - name: Composer, build database and flush cache
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ${{ secrets.REMOTE_DIR }}
            /usr/bin/php7.4 composer.phar install
            /usr/bin/php7.4 vendor/silverstripe/framework/cli-script.php dev/build flush=1
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          privateKey: ${{ secrets.SSH_KEY}}
