name: Deploy via SSH

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "./"
          target: "${{ secrets.REMOTE_DIR }}"
          script: "/usr/bin/php7.4 ${{ secrets.REMOTE_DIR }}/vendor/silverstripe/framework/cli-script.php dev/build flush=1"